import path from 'path';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { authenticate } from './middleware/auth';
import { metricsMiddleware, metricsHandler } from './middleware/metrics';
import { requestLoggerMiddleware } from './middleware/request-logger';
import { healthRouter } from './modules/health/health.routes';
import { authRouter } from './modules/auth/auth.routes';
import { organizationsRouter } from './modules/organizations/organizations.routes';
import { adminRouter } from './modules/admin/admin.routes';
import { orgUsersRouter } from './modules/org-users/org-users.routes';
import { rolesRouter } from './modules/roles/roles.routes';
import { farmsRouter } from './modules/farms/farms.routes';
import { producersRouter } from './modules/producers/producers.routes';
import { carRouter } from './modules/car/car.routes';
import { dashboardRouter } from './modules/dashboard/dashboard.routes';
import { animalsRouter } from './modules/animals/animals.routes';
import { animalLotsRouter } from './modules/animals/animal-lots.routes';
import { animalWeighingRouter } from './modules/animals/animal-weighing.routes';
import { animalHealthRouter } from './modules/animals/animal-health.routes';
import { animalReproductiveRouter } from './modules/animals/animal-reproductive.routes';
import { animalMovementsRouter } from './modules/animals/animal-movements.routes';
import { farmLocationsRouter } from './modules/animals/farm-locations.routes';
import { fieldOperationsRouter } from './modules/field-operations/field-operations.routes';
import { cultivarsRouter } from './modules/cultivars/cultivars.routes';
import { pesticideApplicationsRouter } from './modules/pesticide-applications/pesticide-applications.routes';
import { fertilizerApplicationsRouter } from './modules/fertilizer-applications/fertilizer-applications.routes';
import { culturalOperationsRouter } from './modules/cultural-operations/cultural-operations.routes';
import { fieldTeamsRouter } from './modules/field-teams/field-teams.routes';
import { teamOperationsRouter } from './modules/team-operations/team-operations.routes';
import { productivityTargetsRouter } from './modules/team-operations/productivity-targets.routes';
import { pestsRouter } from './modules/pests/pests.routes';
import { monitoringPointsRouter } from './modules/monitoring-points/monitoring-points.routes';
import { monitoringRecordsRouter } from './modules/monitoring-records/monitoring-records.routes';
import { monitoringReportsRouter } from './modules/monitoring-reports/monitoring-reports.routes';
import { operationTypesRouter } from './modules/operation-types/operation-types.routes';
import { phenologicalRecordsRouter } from './modules/phenological-records/phenological-records.routes';
import { plantingRouter } from './modules/planting-operations/planting-operations.routes';
import { soilPrepRouter } from './modules/soil-prep-operations/soil-prep-operations.routes';
import { grainHarvestsRouter } from './modules/grain-harvests/grain-harvests.routes';
import { moistureStandardsRouter } from './modules/grain-harvests/moisture-standards.routes';
import { coffeeHarvestsRouter } from './modules/coffee-harvests/coffee-harvests.routes';
import { productivityMapRouter } from './modules/productivity-map/productivity-map.routes';
import { orangeHarvestsRouter } from './modules/orange-harvests/orange-harvests.routes';
import { measurementUnitsRouter } from './modules/measurement-units/measurement-units.routes';
import { productsRouter } from './modules/products/products.routes';
import { stockEntriesRouter } from './modules/stock-entries/stock-entries.routes';
import { stockOutputsRouter } from './modules/stock-outputs/stock-outputs.routes';
import { stockAlertsRouter } from './modules/stock-alerts/stock-alerts.routes';
import { stockInventoriesRouter } from './modules/stock-inventories/stock-inventories.routes';
import { pesticidePrescriptionsRouter } from './modules/pesticide-prescriptions/pesticide-prescriptions.routes';
import { conversionHistoryRouter } from './modules/conversion-history/conversion-history.routes';
import { costCentersRouter } from './modules/cost-centers/cost-centers.routes';
import { harvestConversionRouter } from './modules/harvest-commercial-conversion/harvest-commercial-conversion.routes';
import { grainDiscountsRouter } from './modules/grain-discounts/grain-discounts.routes';
import { diseasesRouter } from './modules/diseases/diseases.routes';
import { treatmentProtocolsRouter } from './modules/treatment-protocols/treatment-protocols.routes';
import { sanitaryProtocolsRouter } from './modules/sanitary-protocols/sanitary-protocols.routes';
import { vaccinationsRouter } from './modules/vaccinations/vaccinations.routes';
import { dewormingsRouter } from './modules/dewormings/dewormings.routes';
import { therapeuticTreatmentsRouter } from './modules/therapeutic-treatments/therapeutic-treatments.routes';
import { animalExamsRouter } from './modules/animal-exams/animal-exams.routes';
import { sanitaryDashboardRouter } from './modules/sanitary-dashboard/sanitary-dashboard.routes';
import { compositeProductsRouter } from './modules/composite-products/composite-products.routes';
import { bullsRouter } from './modules/bulls/bulls.routes';
import { reproductiveReleasesRouter } from './modules/reproductive-releases/reproductive-releases.routes';
import { heatRecordsRouter } from './modules/heat-records/heat-records.routes';
import { matingPlansRouter } from './modules/mating-plans/mating-plans.routes';
import { iatfProtocolsRouter } from './modules/iatf-protocols/iatf-protocols.routes';
import { iatfExecutionRouter } from './modules/iatf-execution/iatf-execution.routes';
import { naturalMatingsRouter } from './modules/natural-matings/natural-matings.routes';
import { pregnancyDiagnosisRouter } from './modules/pregnancy-diagnosis/pregnancy-diagnosis.routes';
import { calvingEventsRouter } from './modules/calving-events/calving-events.routes';
import { weaningRouter } from './modules/weaning/weaning.routes';
import { milkingRecordsRouter } from './modules/milking-records/milking-records.routes';
import { milkAnalysisRouter } from './modules/milk-analysis/milk-analysis.routes';
import { mastitisRouter } from './modules/mastitis/mastitis.routes';
import { milkTanksRouter } from './modules/milk-tanks/milk-tanks.routes';
import { lactationsRouter } from './modules/lactations/lactations.routes';
import { milkDashboardRouter } from './modules/milk-dashboard/milk-dashboard.routes';
import { feedIngredientsRouter } from './modules/feed-ingredients/feed-ingredients.routes';
import { dietsRouter } from './modules/diets/diets.routes';
import { feedingRecordsRouter } from './modules/feeding-records/feeding-records.routes';
import { bankAccountsRouter } from './modules/bank-accounts/bank-accounts.routes';
import { payablesRouter } from './modules/payables/payables.routes';
import { receivablesRouter } from './modules/receivables/receivables.routes';
import { payablesAgingRouter } from './modules/payables-aging/payables-aging.routes';
import { financialDashboardRouter } from './modules/financial-dashboard/financial-dashboard.routes';
import { transfersRouter } from './modules/transfers/transfers.routes';
import { checksRouter } from './modules/checks/checks.routes';
import { creditCardsRouter } from './modules/credit-cards/credit-cards.routes';
import { ruralPropertiesRouter } from './modules/rural-properties/rural-properties.routes';
import { cashflowRouter } from './modules/cashflow/cashflow.routes';
import { reconciliationRouter } from './modules/reconciliation/reconciliation.routes';
import { ruralCreditRouter } from './modules/rural-credit/rural-credit.routes';
import { suppliersRouter } from './modules/suppliers/suppliers.routes';
import { purchaseRequestsRouter } from './modules/purchase-requests/purchase-requests.routes';
import { approvalRulesRouter } from './modules/approval-rules/approval-rules.routes';
import { notificationsRouter } from './modules/notifications/notifications.routes';
import { quotationsRouter } from './modules/quotations/quotations.routes';
import { purchaseOrdersRouter } from './modules/purchase-orders/purchase-orders.routes';
import { goodsReceiptsRouter } from './modules/goods-receipts/goods-receipts.routes';
import { goodsReturnsRouter } from './modules/goods-returns/goods-returns.routes';
import { purchaseBudgetsRouter } from './modules/purchase-budgets/purchase-budgets.routes';
import { savingAnalysisRouter } from './modules/saving-analysis/saving-analysis.routes';
import { purchasingKanbanRouter } from './modules/purchasing-kanban/purchasing-kanban.routes';
import { purchasingDashboardRouter } from './modules/purchasing-dashboard/purchasing-dashboard.routes';
import { notificationPreferencesRouter } from './modules/notification-preferences/notification-preferences.routes';
import { assetsRouter } from './modules/assets/assets.routes';
import { assetDocumentsRouter } from './modules/assets/asset-documents.routes';
import { biologicalAssetsRouter } from './modules/biological-assets/biological-assets.routes';
import { fuelRecordsRouter } from './modules/fuel-records/fuel-records.routes';
import { meterReadingsRouter } from './modules/meter-readings/meter-readings.routes';
import { depreciationRouter } from './modules/depreciation/depreciation.routes';
import { animalOwnershipsRouter } from './modules/animal-ownerships/animal-ownerships.routes';
import { animalExitsRouter } from './modules/animal-exits/animal-exits.routes';
import { workOrdersRouter } from './modules/work-orders/work-orders.routes';
import { maintenancePlansRouter } from './modules/maintenance-plans/maintenance-plans.routes';
import { sparePartsRouter } from './modules/spare-parts/spare-parts.routes';
import { maintenanceProvisionsRouter } from './modules/maintenance-provisions/maintenance-provisions.routes';
import { assetAcquisitionsRouter } from './modules/asset-acquisitions/asset-acquisitions.routes';
import { assetDisposalsRouter } from './modules/asset-disposals/asset-disposals.routes';
import { assetFarmTransfersRouter } from './modules/asset-farm-transfers/asset-farm-transfers.routes';
import { assetInventoryRouter } from './modules/asset-inventory/asset-inventory.routes';
import { operationalCostRouter } from './modules/assets/asset-operational-cost.routes';
import { assetRenovationsRouter } from './modules/asset-renovations/asset-renovations.routes';
import { assetWipRouter } from './modules/asset-wip/asset-wip.routes';
import { assetReportsRouter } from './modules/asset-reports/asset-reports.routes';
import { assetLeasingsRouter } from './modules/asset-leasings/asset-leasings.routes';
import { assetTradeInsRouter } from './modules/asset-trade-ins/asset-trade-ins.routes';
import { employeesRouter } from './modules/employees/employees.routes';
import { employeeContractsRouter } from './modules/employee-contracts/employee-contracts.routes';
import { positionsRouter } from './modules/positions/positions.routes';
import { workSchedulesRouter } from './modules/work-schedules/work-schedules.routes';
import { employeeMovementsRouter } from './modules/employee-movements/employee-movements.routes';
import { payrollRubricasRouter } from './modules/payroll-rubricas/payroll-rubricas.routes';
import { payrollTablesRouter } from './modules/payroll-tables/payroll-tables.routes';
import { timeEntriesRouter } from './modules/time-entries/time-entries.routes';
import { overtimeBankRouter } from './modules/overtime-bank/overtime-bank.routes';
import { timesheetsRouter } from './modules/timesheets/timesheets.routes';
import { salaryAdvancesRouter } from './modules/salary-advances/salary-advances.routes';
import { payrollRunsRouter } from './modules/payroll-runs/payroll-runs.routes';
import { vacationSchedulesRouter } from './modules/vacation-schedules/vacation-schedules.routes';
import { employeeAbsencesRouter } from './modules/employee-absences/employee-absences.routes';
import { payrollProvisionsRouter } from './modules/payroll-provisions/payroll-provisions.routes';
import { employeeTerminationsRouter } from './modules/employee-terminations/employee-terminations.routes';

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(metricsMiddleware);
app.use(requestLoggerMiddleware);

app.get('/metrics', metricsHandler);

// Serve uploaded files (photos, attachments) — requires authentication
app.use('/api/uploads', authenticate, express.static(path.join(process.cwd(), 'uploads')));

app.use('/api', healthRouter);
app.use('/api', authRouter);
app.use('/api', organizationsRouter);
app.use('/api', adminRouter);
app.use('/api', orgUsersRouter);
app.use('/api', rolesRouter);
app.use('/api', farmsRouter);
app.use('/api', ruralPropertiesRouter);
app.use('/api', producersRouter);
app.use('/api', carRouter);
app.use('/api', dashboardRouter);
app.use('/api', animalsRouter);
app.use('/api', animalLotsRouter);
app.use('/api', animalWeighingRouter);
app.use('/api', animalHealthRouter);
app.use('/api', animalReproductiveRouter);
app.use('/api', animalMovementsRouter);
app.use('/api', farmLocationsRouter);
app.use('/api', fieldOperationsRouter);
app.use('/api', cultivarsRouter);
app.use('/api', pesticideApplicationsRouter);
app.use('/api', fertilizerApplicationsRouter);
app.use('/api', culturalOperationsRouter);
app.use('/api', fieldTeamsRouter);
app.use('/api', teamOperationsRouter);
app.use('/api', productivityTargetsRouter);
app.use('/api', pestsRouter);
app.use('/api', monitoringPointsRouter);
app.use('/api', monitoringRecordsRouter);
app.use('/api', monitoringReportsRouter);
app.use('/api', operationTypesRouter);
app.use('/api', phenologicalRecordsRouter);
app.use('/api', plantingRouter);
app.use('/api', soilPrepRouter);
app.use('/api', grainHarvestsRouter);
app.use('/api', moistureStandardsRouter);
app.use('/api', coffeeHarvestsRouter);
app.use('/api', productivityMapRouter);
app.use('/api', orangeHarvestsRouter);
app.use('/api', measurementUnitsRouter);
app.use('/api', productsRouter);
app.use('/api', stockEntriesRouter);
app.use('/api', stockOutputsRouter);
app.use('/api', stockAlertsRouter);
app.use('/api', stockInventoriesRouter);
app.use('/api', pesticidePrescriptionsRouter);
app.use('/api', conversionHistoryRouter);
app.use('/api', costCentersRouter);
app.use('/api', harvestConversionRouter);
app.use('/api', grainDiscountsRouter);
app.use('/api', diseasesRouter);
app.use('/api', treatmentProtocolsRouter);
app.use('/api', sanitaryProtocolsRouter);
app.use('/api', vaccinationsRouter);
app.use('/api', dewormingsRouter);
app.use('/api', therapeuticTreatmentsRouter);
app.use('/api', animalExamsRouter);
app.use('/api', sanitaryDashboardRouter);
app.use('/api', compositeProductsRouter);
app.use('/api', bullsRouter);
app.use('/api', reproductiveReleasesRouter);
app.use('/api', heatRecordsRouter);
app.use('/api', matingPlansRouter);
app.use('/api', iatfProtocolsRouter);
app.use('/api', iatfExecutionRouter);
app.use('/api', naturalMatingsRouter);
app.use('/api', pregnancyDiagnosisRouter);
app.use('/api', calvingEventsRouter);
app.use('/api', weaningRouter);
app.use('/api', milkingRecordsRouter);
app.use('/api', milkAnalysisRouter);
app.use('/api', mastitisRouter);
app.use('/api', milkTanksRouter);
app.use('/api', lactationsRouter);
app.use('/api', milkDashboardRouter);
app.use('/api', feedIngredientsRouter);
app.use('/api', dietsRouter);
app.use('/api', feedingRecordsRouter);
app.use('/api', bankAccountsRouter);
app.use('/api', payablesRouter);
app.use('/api', receivablesRouter);
app.use('/api', payablesAgingRouter);
app.use('/api', financialDashboardRouter);
app.use('/api', transfersRouter);
app.use('/api', checksRouter);
app.use('/api', creditCardsRouter);
app.use('/api', cashflowRouter);
app.use('/api', reconciliationRouter);
app.use('/api', ruralCreditRouter);
app.use('/api', suppliersRouter);
app.use('/api', purchaseRequestsRouter);
app.use('/api', approvalRulesRouter);
app.use('/api', notificationsRouter);
app.use('/api', quotationsRouter);
app.use('/api', purchaseOrdersRouter);
app.use('/api', goodsReceiptsRouter);
app.use('/api', goodsReturnsRouter);
app.use('/api', purchaseBudgetsRouter);
app.use('/api', savingAnalysisRouter);
app.use('/api', purchasingKanbanRouter);
app.use('/api', purchasingDashboardRouter);
app.use('/api', notificationPreferencesRouter);
app.use('/api', assetsRouter);
app.use('/api', assetDocumentsRouter);
app.use('/api', biologicalAssetsRouter);
app.use('/api', fuelRecordsRouter);
app.use('/api', meterReadingsRouter);
app.use('/api', depreciationRouter);
app.use('/api', animalOwnershipsRouter);
app.use('/api', animalExitsRouter);
app.use('/api', workOrdersRouter);
app.use('/api', maintenancePlansRouter);
app.use('/api', sparePartsRouter);
app.use('/api', maintenanceProvisionsRouter);
app.use('/api', assetAcquisitionsRouter);
app.use('/api', assetDisposalsRouter);
app.use('/api', assetFarmTransfersRouter);
app.use('/api', assetInventoryRouter);
app.use('/api', operationalCostRouter);
app.use('/api', assetRenovationsRouter);
app.use('/api', assetWipRouter);
app.use('/api', assetReportsRouter);
app.use('/api', assetLeasingsRouter);
app.use('/api', assetTradeInsRouter);
app.use('/api', employeesRouter);
app.use('/api', employeeContractsRouter);
app.use('/api', positionsRouter);
app.use('/api', workSchedulesRouter);
app.use('/api', employeeMovementsRouter);
app.use('/api', payrollRubricasRouter);
app.use('/api', payrollTablesRouter);
app.use('/api', timeEntriesRouter);
app.use('/api', overtimeBankRouter);
app.use('/api', timesheetsRouter);
app.use('/api', salaryAdvancesRouter);
app.use('/api', payrollRunsRouter);
app.use('/api', vacationSchedulesRouter);
app.use('/api', employeeAbsencesRouter);
app.use('/api', payrollProvisionsRouter);
app.use('/api', employeeTerminationsRouter);

export { app };
