import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { metricsMiddleware, metricsHandler } from './middleware/metrics';
import { requestLoggerMiddleware } from './middleware/request-logger';
import { healthRouter } from './modules/health/health.routes';
import { authRouter } from './modules/auth/auth.routes';
import { organizationsRouter } from './modules/organizations/organizations.routes';
import { adminRouter } from './modules/admin/admin.routes';
import { orgUsersRouter } from './modules/org-users/org-users.routes';
import { rolesRouter } from './modules/roles/roles.routes';
import { farmsRouter } from './modules/farms/farms.routes';
import { producersRouter } from './modules/producers/producers.routes';
import { carRouter } from './modules/car/car.routes';
import { dashboardRouter } from './modules/dashboard/dashboard.routes';
import { animalsRouter } from './modules/animals/animals.routes';
import { animalLotsRouter } from './modules/animals/animal-lots.routes';
import { animalWeighingRouter } from './modules/animals/animal-weighing.routes';
import { animalHealthRouter } from './modules/animals/animal-health.routes';
import { animalReproductiveRouter } from './modules/animals/animal-reproductive.routes';
import { animalMovementsRouter } from './modules/animals/animal-movements.routes';
import { farmLocationsRouter } from './modules/animals/farm-locations.routes';
import { fieldOperationsRouter } from './modules/field-operations/field-operations.routes';
import { cultivarsRouter } from './modules/cultivars/cultivars.routes';
import { pesticideApplicationsRouter } from './modules/pesticide-applications/pesticide-applications.routes';
import { fertilizerApplicationsRouter } from './modules/fertilizer-applications/fertilizer-applications.routes';
import { culturalOperationsRouter } from './modules/cultural-operations/cultural-operations.routes';
import { fieldTeamsRouter } from './modules/field-teams/field-teams.routes';
import { teamOperationsRouter } from './modules/team-operations/team-operations.routes';
import { productivityTargetsRouter } from './modules/team-operations/productivity-targets.routes';
import { pestsRouter } from './modules/pests/pests.routes';
import { monitoringPointsRouter } from './modules/monitoring-points/monitoring-points.routes';
import { monitoringRecordsRouter } from './modules/monitoring-records/monitoring-records.routes';
import { monitoringReportsRouter } from './modules/monitoring-reports/monitoring-reports.routes';
import { operationTypesRouter } from './modules/operation-types/operation-types.routes';
import { phenologicalRecordsRouter } from './modules/phenological-records/phenological-records.routes';
import { plantingRouter } from './modules/planting-operations/planting-operations.routes';
import { soilPrepRouter } from './modules/soil-prep-operations/soil-prep-operations.routes';
import { grainHarvestsRouter } from './modules/grain-harvests/grain-harvests.routes';
import { moistureStandardsRouter } from './modules/grain-harvests/moisture-standards.routes';
import { coffeeHarvestsRouter } from './modules/coffee-harvests/coffee-harvests.routes';
import { orangeHarvestsRouter } from './modules/orange-harvests/orange-harvests.routes';
import { measurementUnitsRouter } from './modules/measurement-units/measurement-units.routes';
import { productsRouter } from './modules/products/products.routes';
import { stockEntriesRouter } from './modules/stock-entries/stock-entries.routes';
import { stockOutputsRouter } from './modules/stock-outputs/stock-outputs.routes';
import { stockAlertsRouter } from './modules/stock-alerts/stock-alerts.routes';
import { stockInventoriesRouter } from './modules/stock-inventories/stock-inventories.routes';
import { pesticidePrescriptionsRouter } from './modules/pesticide-prescriptions/pesticide-prescriptions.routes';
import { conversionHistoryRouter } from './modules/conversion-history/conversion-history.routes';
import { costCentersRouter } from './modules/cost-centers/cost-centers.routes';
import { harvestConversionRouter } from './modules/harvest-commercial-conversion/harvest-commercial-conversion.routes';
import { grainDiscountsRouter } from './modules/grain-discounts/grain-discounts.routes';
import { diseasesRouter } from './modules/diseases/diseases.routes';
import { treatmentProtocolsRouter } from './modules/treatment-protocols/treatment-protocols.routes';
import { sanitaryProtocolsRouter } from './modules/sanitary-protocols/sanitary-protocols.routes';
import { vaccinationsRouter } from './modules/vaccinations/vaccinations.routes';
import { dewormingsRouter } from './modules/dewormings/dewormings.routes';
import { therapeuticTreatmentsRouter } from './modules/therapeutic-treatments/therapeutic-treatments.routes';
import { animalExamsRouter } from './modules/animal-exams/animal-exams.routes';
import { sanitaryDashboardRouter } from './modules/sanitary-dashboard/sanitary-dashboard.routes';
import { compositeProductsRouter } from './modules/composite-products/composite-products.routes';
import { bullsRouter } from './modules/bulls/bulls.routes';
import { reproductiveReleasesRouter } from './modules/reproductive-releases/reproductive-releases.routes';
import { heatRecordsRouter } from './modules/heat-records/heat-records.routes';
import { matingPlansRouter } from './modules/mating-plans/mating-plans.routes';
import { iatfProtocolsRouter } from './modules/iatf-protocols/iatf-protocols.routes';
import { iatfExecutionRouter } from './modules/iatf-execution/iatf-execution.routes';
import { naturalMatingsRouter } from './modules/natural-matings/natural-matings.routes';
import { pregnancyDiagnosisRouter } from './modules/pregnancy-diagnosis/pregnancy-diagnosis.routes';
import { calvingEventsRouter } from './modules/calving-events/calving-events.routes';
import { weaningRouter } from './modules/weaning/weaning.routes';
import { milkingRecordsRouter } from './modules/milking-records/milking-records.routes';
import { milkAnalysisRouter } from './modules/milk-analysis/milk-analysis.routes';
import { mastitisRouter } from './modules/mastitis/mastitis.routes';
import { milkTanksRouter } from './modules/milk-tanks/milk-tanks.routes';
import { lactationsRouter } from './modules/lactations/lactations.routes';
import { milkDashboardRouter } from './modules/milk-dashboard/milk-dashboard.routes';

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(metricsMiddleware);
app.use(requestLoggerMiddleware);

app.get('/metrics', metricsHandler);
app.use('/api', healthRouter);
app.use('/api', authRouter);
app.use('/api', organizationsRouter);
app.use('/api', adminRouter);
app.use('/api', orgUsersRouter);
app.use('/api', rolesRouter);
app.use('/api', farmsRouter);
app.use('/api', producersRouter);
app.use('/api', carRouter);
app.use('/api', dashboardRouter);
app.use('/api', animalsRouter);
app.use('/api', animalLotsRouter);
app.use('/api', animalWeighingRouter);
app.use('/api', animalHealthRouter);
app.use('/api', animalReproductiveRouter);
app.use('/api', animalMovementsRouter);
app.use('/api', farmLocationsRouter);
app.use('/api', fieldOperationsRouter);
app.use('/api', cultivarsRouter);
app.use('/api', pesticideApplicationsRouter);
app.use('/api', fertilizerApplicationsRouter);
app.use('/api', culturalOperationsRouter);
app.use('/api', fieldTeamsRouter);
app.use('/api', teamOperationsRouter);
app.use('/api', productivityTargetsRouter);
app.use('/api', pestsRouter);
app.use('/api', monitoringPointsRouter);
app.use('/api', monitoringRecordsRouter);
app.use('/api', monitoringReportsRouter);
app.use('/api', operationTypesRouter);
app.use('/api', phenologicalRecordsRouter);
app.use('/api', plantingRouter);
app.use('/api', soilPrepRouter);
app.use('/api', grainHarvestsRouter);
app.use('/api', moistureStandardsRouter);
app.use('/api', coffeeHarvestsRouter);
app.use('/api', orangeHarvestsRouter);
app.use('/api', measurementUnitsRouter);
app.use('/api', productsRouter);
app.use('/api', stockEntriesRouter);
app.use('/api', stockOutputsRouter);
app.use('/api', stockAlertsRouter);
app.use('/api', stockInventoriesRouter);
app.use('/api', pesticidePrescriptionsRouter);
app.use('/api', conversionHistoryRouter);
app.use('/api', costCentersRouter);
app.use('/api', harvestConversionRouter);
app.use('/api', grainDiscountsRouter);
app.use('/api', diseasesRouter);
app.use('/api', treatmentProtocolsRouter);
app.use('/api', sanitaryProtocolsRouter);
app.use('/api', vaccinationsRouter);
app.use('/api', dewormingsRouter);
app.use('/api', therapeuticTreatmentsRouter);
app.use('/api', animalExamsRouter);
app.use('/api', sanitaryDashboardRouter);
app.use('/api', compositeProductsRouter);
app.use('/api', bullsRouter);
app.use('/api', reproductiveReleasesRouter);
app.use('/api', heatRecordsRouter);
app.use('/api', matingPlansRouter);
app.use('/api', iatfProtocolsRouter);
app.use('/api', iatfExecutionRouter);
app.use('/api', naturalMatingsRouter);
app.use('/api', pregnancyDiagnosisRouter);
app.use('/api', calvingEventsRouter);
app.use('/api', weaningRouter);
app.use('/api', milkingRecordsRouter);
app.use('/api', milkAnalysisRouter);
app.use('/api', mastitisRouter);
app.use('/api', milkTanksRouter);
app.use('/api', lactationsRouter);
app.use('/api', milkDashboardRouter);

export { app };
