// ─── Rural COA Template (CFC/Embrapa Standard) ────────────────────────────────
// COA-02: CFC/Embrapa rural chart of accounts with SPED L300R mapping.
//
// Notes:
// - Follows CFC/Embrapa rural accounting standard for Brazilian agribusiness
// - SPED L300R codes: ECD block format for analytic accounts
// - The existing ACCOUNT_CODES in accounting-entries.types.ts uses 6.x codes (legacy).
//   These legacy codes are included here as well. When Phase 37 wires accounting rules,
//   the ACCOUNT_CODES constants will be updated to reference the standard CFC numbering.
// - isFairValueAdj marks accounts related to fair value (CPC 29 biological assets)

import type { SeedAccountDef } from './chart-of-accounts.types';

export const RURAL_COA_TEMPLATE: SeedAccountDef[] = [
  // ═══════════════════════════════════════════════════════════════════
  // LEVEL 1 — Main Groups (5 accounts, isSynthetic: true)
  // ═══════════════════════════════════════════════════════════════════

  {
    code: '1',
    name: 'ATIVO',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 1,
  },
  {
    code: '2',
    name: 'PASSIVO',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 1,
  },
  {
    code: '3',
    name: 'PATRIMONIO LIQUIDO',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 1,
  },
  {
    code: '4',
    name: 'RECEITAS',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 1,
  },
  {
    code: '5',
    name: 'DESPESAS E CUSTOS',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 1,
  },
  // Legacy expense group (matches existing ACCOUNT_CODES 6.x)
  {
    code: '6',
    name: 'DESPESAS COM PESSOAL (LEGADO)',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 1,
  },

  // ═══════════════════════════════════════════════════════════════════
  // LEVEL 2 — Sub-groups
  // ═══════════════════════════════════════════════════════════════════

  // ATIVO
  {
    code: '1.1',
    name: 'Ativo Circulante',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '1',
  },
  {
    code: '1.2',
    name: 'Ativo Nao Circulante',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '1',
  },

  // PASSIVO
  {
    code: '2.1',
    name: 'Passivo Circulante',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '2',
  },
  {
    code: '2.2',
    name: 'Passivo Nao Circulante',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '2',
  },

  // PATRIMONIO LIQUIDO
  {
    code: '3.1',
    name: 'Capital Social',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '3',
  },
  {
    code: '3.2',
    name: 'Reservas de Lucro',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '3',
  },

  // RECEITAS
  {
    code: '4.1',
    name: 'Receitas Agropecuarias',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '4',
  },
  {
    code: '4.2',
    name: 'Outras Receitas Operacionais',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '4',
  },
  {
    code: '4.3',
    name: 'Receitas Financeiras',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '4',
  },

  // DESPESAS E CUSTOS
  {
    code: '5.1',
    name: 'Custo dos Produtos Vendidos (CPV)',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '5',
  },
  {
    code: '5.2',
    name: 'Despesas Operacionais',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '5',
  },
  {
    code: '5.3',
    name: 'Despesas Financeiras',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '5',
  },

  // Legacy 6.x sub-groups (matching ACCOUNT_CODES)
  {
    code: '6.1',
    name: 'Despesas com Salarios e Encargos',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 2,
    parentCode: '6',
  },

  // ═══════════════════════════════════════════════════════════════════
  // LEVEL 3 — Sub-sub-groups (rural-specific)
  // ═══════════════════════════════════════════════════════════════════

  // Ativo Circulante sub-groups
  {
    code: '1.1.01',
    name: 'Disponibilidades',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.1',
  },
  {
    code: '1.1.02',
    name: 'Creditos a Receber',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.1',
  },
  {
    code: '1.1.03',
    name: 'Estoques',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.1',
  },
  {
    code: '1.1.04',
    name: 'Credito Rural a Receber',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.1',
  },

  // Ativo Nao Circulante sub-groups (CPC 29 biological assets)
  {
    code: '1.2.01',
    name: 'Ativo Biologico',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.2',
  },
  {
    code: '1.2.02',
    name: 'Culturas em Formacao',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.2',
  },
  {
    code: '1.2.03',
    name: 'Imobilizado Rural',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.2',
  },
  {
    code: '1.2.04',
    name: 'Intangivel',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '1.2',
  },

  // Passivo Circulante sub-groups
  {
    code: '2.1.01',
    name: 'Obrigacoes Trabalhistas',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.1',
  },
  {
    code: '2.1.02',
    name: 'Obrigacoes Tributarias',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.1',
  },
  {
    code: '2.1.03',
    name: 'Obrigacoes Previdenciarias',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.1',
  },
  {
    code: '2.1.04',
    name: 'Fornecedores e Contas a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.1',
  },

  // Passivo Nao Circulante sub-groups
  {
    code: '2.2.01',
    name: 'Provisoes de Longo Prazo',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.2',
  },
  {
    code: '2.2.02',
    name: 'Financiamentos Rurais',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '2.2',
  },

  // Capital Social sub-groups
  {
    code: '3.1.01',
    name: 'Capital Social Subscrito',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '3.1',
  },
  {
    code: '3.1.02',
    name: 'Resultados Acumulados',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '3.1',
  },

  // Receitas sub-groups
  {
    code: '4.1.01',
    name: 'Receita Venda Graos',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '4.1',
  },
  {
    code: '4.1.02',
    name: 'Receita Venda Pecuaria',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '4.1',
  },
  {
    code: '4.1.03',
    name: 'Variacao Valor Justo Ativo Biologico',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '4.1',
    isFairValueAdj: true,
  },
  {
    code: '4.1.04',
    name: 'Receita Leite e Derivados',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '4.1',
  },

  // CPV sub-groups
  {
    code: '5.1.01',
    name: 'Custo Producao Vegetal',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '5.1',
  },
  {
    code: '5.1.02',
    name: 'Custo Producao Pecuaria',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '5.1',
  },

  // Despesas Operacionais sub-groups
  {
    code: '5.2.01',
    name: 'Despesas Administrativas',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '5.2',
  },
  {
    code: '5.2.02',
    name: 'Despesas com Pessoal',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '5.2',
  },
  {
    code: '5.2.03',
    name: 'Depreciacoes e Amortizacoes',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: true,
    level: 3,
    parentCode: '5.2',
  },

  // Legacy 6.x sub-sub-groups
  {
    code: '6.1.01',
    name: 'Despesas com Salarios Legado',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '6.1',
    allowManualEntry: true,
  },
  {
    code: '6.1.02',
    name: 'Despesas Encargos Sociais Legado',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '6.1',
    allowManualEntry: true,
  },
  {
    code: '6.1.03',
    name: 'Desp. Prov. Ferias Legado',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '6.1',
    allowManualEntry: true,
  },
  {
    code: '6.1.04',
    name: 'Desp. Prov. 13o Legado',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '6.1',
    allowManualEntry: true,
  },
  {
    code: '6.1.05',
    name: 'Despesas INSS/IRRF Legado',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '6.1',
    allowManualEntry: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // LEVEL 4 — Analytic Groups (synthetic: true, no manual entry)
  // ═══════════════════════════════════════════════════════════════════

  // Disponibilidades
  {
    code: '1.1.01.001',
    name: 'Caixa',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.01',
    spedRefCode: '1.01.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.1.01.002',
    name: 'Bancos c/ Movimento',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.01',
    spedRefCode: '1.01.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '1.1.01.003',
    name: 'Aplicacoes Financeiras de Curto Prazo',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.01',
    spedRefCode: '1.01.01.02.01',
    allowManualEntry: true,
  },

  // Creditos a Receber
  {
    code: '1.1.02.001',
    name: 'Contas a Receber - Graos',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.02',
    spedRefCode: '1.01.03.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.1.02.002',
    name: 'Contas a Receber - Pecuaria',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.02',
    spedRefCode: '1.01.03.01.02',
    allowManualEntry: true,
  },
  {
    code: '1.1.02.003',
    name: '(-) PDD - Perdas em Creditos',
    accountType: 'ATIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.02',
    spedRefCode: '1.01.03.02.01',
    allowManualEntry: true,
  },
  {
    code: '1.1.02.004',
    name: 'FUNRURAL a Recuperar',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.02',
    spedRefCode: '1.01.03.03.01',
    allowManualEntry: true,
  },

  // Estoques
  {
    code: '1.1.03.001',
    name: 'Estoque de Insumos Agricolas',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.03',
    spedRefCode: '1.01.04.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.1.03.002',
    name: 'Estoque de Combustiveis',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.03',
    spedRefCode: '1.01.04.01.02',
    allowManualEntry: true,
  },
  {
    code: '1.1.03.003',
    name: 'Estoque de Graos Colhidos',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.03',
    spedRefCode: '1.01.04.02.01',
    allowManualEntry: true,
  },

  // Credito Rural
  {
    code: '1.1.04.001',
    name: 'Credito Rural - PRONAF',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.04',
    spedRefCode: '1.01.06.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.1.04.002',
    name: 'Credito Rural - PRONAMP',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.1.04',
    spedRefCode: '1.01.06.01.02',
    allowManualEntry: true,
  },

  // Ativo Biologico (CPC 29)
  {
    code: '1.2.01.001',
    name: 'Ativo Biologico Rebanho Bovino',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.01',
    spedRefCode: '1.02.03.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.2.01.002',
    name: 'Ajuste VJL Ativo Biologico',
    accountType: 'ATIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.01',
    spedRefCode: '1.02.03.01.02',
    isFairValueAdj: true,
    allowManualEntry: true,
  },
  {
    code: '1.2.01.003',
    name: 'Ativo Biologico Lavoura Permanente',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.01',
    spedRefCode: '1.02.03.02.01',
    allowManualEntry: true,
  },

  // Culturas em Formacao
  {
    code: '1.2.02.001',
    name: 'Culturas Anuais em Formacao',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.02',
    spedRefCode: '1.02.04.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.2.02.002',
    name: 'Culturas Perenes em Formacao',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.02',
    spedRefCode: '1.02.04.01.02',
    allowManualEntry: true,
  },

  // Imobilizado Rural
  {
    code: '1.2.03.001',
    name: 'Terras e Terrenos',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.03',
    spedRefCode: '1.02.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '1.2.03.002',
    name: 'Maquinas e Equipamentos',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.03',
    spedRefCode: '1.02.01.02.01',
    allowManualEntry: true,
  },
  {
    code: '1.2.03.003',
    name: 'Veiculos e Tratores',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.03',
    spedRefCode: '1.02.01.02.02',
    allowManualEntry: true,
  },
  {
    code: '1.2.03.004',
    name: 'Benfeitorias e Instalacoes',
    accountType: 'ATIVO' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.03',
    spedRefCode: '1.02.01.03.01',
    allowManualEntry: true,
  },
  {
    code: '1.2.03.005',
    name: '(-) Depreciacao Acumulada',
    accountType: 'ATIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '1.2.03',
    spedRefCode: '1.02.01.04.01',
    allowManualEntry: true,
  },

  // Passivo Circulante — Obrigacoes Trabalhistas
  {
    code: '2.1.01.001',
    name: 'Salarios a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.01',
    spedRefCode: '2.01.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.1.01.002',
    name: 'Ferias a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.01',
    spedRefCode: '2.01.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '2.1.01.003',
    name: '13o Salario a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.01',
    spedRefCode: '2.01.01.01.03',
    allowManualEntry: true,
  },

  // Passivo Circulante — Obrigacoes Tributarias
  {
    code: '2.1.02.001',
    name: 'Encargos a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.02',
    spedRefCode: '2.01.02.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.1.02.002',
    name: 'IRRF a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.02',
    spedRefCode: '2.01.02.01.02',
    allowManualEntry: true,
  },
  {
    code: '2.1.02.003',
    name: 'ITR a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.02',
    spedRefCode: '2.01.02.01.03',
    allowManualEntry: true,
  },

  // Passivo Circulante — Obrigacoes Previdenciarias
  {
    code: '2.1.03.001',
    name: 'INSS/IRRF a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.03',
    spedRefCode: '2.01.03.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.1.03.002',
    name: 'FGTS a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.03',
    spedRefCode: '2.01.03.01.02',
    allowManualEntry: true,
  },
  {
    code: '2.1.03.003',
    name: 'FUNRURAL a Recolher',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.03',
    spedRefCode: '2.01.03.02.01',
    allowManualEntry: true,
  },

  // Fornecedores
  {
    code: '2.1.04.001',
    name: 'Fornecedores - Insumos',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.04',
    spedRefCode: '2.01.04.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.1.04.002',
    name: 'Fornecedores - Servicos',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.1.04',
    spedRefCode: '2.01.04.01.02',
    allowManualEntry: true,
  },

  // Passivo Nao Circulante — Provisoes
  {
    code: '2.2.01.001',
    name: 'Provisao Ferias a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.2.01',
    spedRefCode: '2.02.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.2.01.002',
    name: 'Provisao 13o a Pagar',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.2.01',
    spedRefCode: '2.02.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '2.2.01.003',
    name: 'Provisao Indenizacoes Trabalhistas',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.2.01',
    spedRefCode: '2.02.01.01.03',
    allowManualEntry: true,
  },

  // Financiamentos Rurais
  {
    code: '2.2.02.001',
    name: 'Emprestimos Bancarios LP',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.2.02',
    spedRefCode: '2.02.02.01.01',
    allowManualEntry: true,
  },
  {
    code: '2.2.02.002',
    name: 'Credito Rural LP - PRONAMP',
    accountType: 'PASSIVO' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '2.2.02',
    spedRefCode: '2.02.02.01.02',
    allowManualEntry: true,
  },

  // Capital Social
  {
    code: '3.1.01.001',
    name: 'Capital Social Integralizado',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '3.1.01',
    spedRefCode: '2.03.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '3.1.02.001',
    name: 'Lucros/Prejuizos Acumulados',
    accountType: 'PL' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '3.1.02',
    spedRefCode: '2.03.05.01.01',
    allowManualEntry: true,
  },

  // Receitas Agropecuarias
  {
    code: '4.1.01.001',
    name: 'Receita Venda Soja',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.01',
    spedRefCode: '3.01.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '4.1.01.002',
    name: 'Receita Venda Milho',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.01',
    spedRefCode: '3.01.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '4.1.01.003',
    name: 'Receita Venda Cafe',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.01',
    spedRefCode: '3.01.01.01.03',
    allowManualEntry: true,
  },
  {
    code: '4.1.02.001',
    name: 'Receita Venda Gado',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.02',
    spedRefCode: '3.01.02.01.01',
    allowManualEntry: true,
  },
  {
    code: '4.1.02.002',
    name: 'Receita Venda Leite',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.02',
    spedRefCode: '3.01.02.01.02',
    allowManualEntry: true,
  },
  {
    code: '4.1.03.001',
    name: 'Variacao VJL Ativo Biologico',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.03',
    spedRefCode: '3.01.03.01.01',
    isFairValueAdj: true,
    allowManualEntry: true,
  },
  {
    code: '4.1.04.001',
    name: 'Receita Venda Laranja',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '4.1.04',
    spedRefCode: '3.01.04.01.01',
    allowManualEntry: true,
  },
  {
    code: '4.3.001',
    name: 'Receitas Financeiras Diversas',
    accountType: 'RECEITA' as const,
    nature: 'CREDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '4.3',
    spedRefCode: '3.02.01.01.01',
    allowManualEntry: true,
  },

  // Custos Producao
  {
    code: '5.1.01.001',
    name: 'Sementes e Mudas',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.01',
    spedRefCode: '4.01.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.1.01.002',
    name: 'Fertilizantes e Corretivos',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.01',
    spedRefCode: '4.01.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '5.1.01.003',
    name: 'Defensivos Agricolas',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.01',
    spedRefCode: '4.01.01.01.03',
    allowManualEntry: true,
  },
  {
    code: '5.1.01.004',
    name: 'Combustiveis e Lubrificantes Agricolas',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.01',
    spedRefCode: '4.01.01.01.04',
    allowManualEntry: true,
  },
  {
    code: '5.1.02.001',
    name: 'Alimentacao Animal',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.02',
    spedRefCode: '4.01.02.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.1.02.002',
    name: 'Medicamentos e Sanidade Animal',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.1.02',
    spedRefCode: '4.01.02.01.02',
    allowManualEntry: true,
  },

  // Despesas Administrativas
  {
    code: '5.2.01.001',
    name: 'Servicos de Terceiros',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.01',
    spedRefCode: '4.02.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.2.01.002',
    name: 'Manutencao de Maquinas',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.01',
    spedRefCode: '4.02.01.01.02',
    allowManualEntry: true,
  },
  {
    code: '5.2.01.003',
    name: 'Seguros',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.01',
    spedRefCode: '4.02.01.01.03',
    allowManualEntry: true,
  },

  // Despesas com Pessoal (standard CFC 5.x)
  {
    code: '5.2.02.001',
    name: 'Despesas com Salarios',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.02',
    spedRefCode: '4.02.02.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.2.02.002',
    name: 'Encargos Sociais (INSS/FGTS)',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.02',
    spedRefCode: '4.02.02.01.02',
    allowManualEntry: true,
  },
  {
    code: '5.2.02.003',
    name: 'Provisao Ferias',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.02',
    spedRefCode: '4.02.02.01.03',
    allowManualEntry: true,
  },
  {
    code: '5.2.02.004',
    name: 'Provisao 13o Salario',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.02',
    spedRefCode: '4.02.02.01.04',
    allowManualEntry: true,
  },
  {
    code: '5.2.02.005',
    name: 'FUNRURAL Patronal',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.02',
    spedRefCode: '4.02.02.01.05',
    allowManualEntry: true,
  },

  // Depreciacoes
  {
    code: '5.2.03.001',
    name: 'Depreciacao Maquinas e Equipamentos',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.03',
    spedRefCode: '4.02.03.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.2.03.002',
    name: 'Depreciacao Benfeitorias',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 4,
    parentCode: '5.2.03',
    spedRefCode: '4.02.03.01.02',
    allowManualEntry: true,
  },

  // Despesas Financeiras
  {
    code: '5.3.001',
    name: 'Juros sobre Financiamentos',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '5.3',
    spedRefCode: '4.03.01.01.01',
    allowManualEntry: true,
  },
  {
    code: '5.3.002',
    name: 'IOF e Tarifas Bancarias',
    accountType: 'DESPESA' as const,
    nature: 'DEVEDORA' as const,
    isSynthetic: false,
    level: 3,
    parentCode: '5.3',
    spedRefCode: '4.03.01.01.02',
    allowManualEntry: true,
  },
];
